before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - ignore:
    - goos: windows
      goarch: arm64

archives:
  - format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: fogfish
      name: iq
    directory: Formula
    goarm: "7"
    homepage:  https://github.com/fogfish/iq
    description: iq (Intelligent Query) is a fast and lightweight CLI for running LLM-powered agents.
    license: MIT
    test: |
      system "#{bin}/iq -v"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqo