name: test
entrypoint: test

jobs:

  life:
    steps:
      - name: life
        uses: life.md

  fea:
    steps:
      - name: fea
        uses: fea.md


  test:
    steps:
      - name: noun
        uses: noun.md

      - name: choice
        uses: choice.md
        switch:
          - when: choice == "life"
            route: life
          - when: choice == "none"
            route: fea
        default: fea

  cycle-test:
    steps:
      - name: cycle
        uses: get-items.md
        foreach:
          job: life
        output: results